### PR TITLE
[WIP] Add sslEnabled to config and pass to mongo client builder

### PR DESCRIPTION
**Pull request by martinpeck**
Potentially still work in progress (WIP) as I've not added tests at this stage. Just wanted to confirm that I'm on the right path here in adding SSL support for the MongoDB sslEnabled config.

### CODE REVIEW

**Comment by martinpeck** [comment]
cc @imedina @wbari @j-coll 

I've added tasks (checkboxes) to the original issue to cover the addition of Tests etc (https://github.com/opencb/opencga/issues/943).

**Comment by j-coll** [comment]
Nice!
In order to use this from OpenCGA branch release-1.4.0, can you make the PR against the branch hotfix-3.7.x ?

**Comment by martinpeck** [comment]
I'm going to re-do this work on the correct branch to avoid lots of messy merging.

**Comment by martinpeck** [comment]
Closing without merging.

**Pull request closed without merging**
